/**
 * DO NOT EDIT THIS DIRECTLY!
 * Generated by @ople/codegen
 */
import { defineBackend, OpleProtocol, OpleCollection, OpleListener, OplePage, OpleRefLike, makeCreator, OpleRef } from "@ople/client"

interface Collections {
  users: OpleCollection<User>
  posts: OpleCollection<Post>
  replies: OpleCollection<Reply>
}

interface Functions {
  loadPosts(pageOptions?: OplePage.Options): Promise<OplePage<Post>>
  loadReplies(parentRef: OpleRefLike<Reply> | OpleRefLike<Post>, pageOptions?: OplePage.Options): Promise<OplePage<Reply>>
  publish(props: { text: string; }): Post
  reply(props: { text: string; post?: OpleRefLike<Post> | undefined; parent?: OpleRefLike<Reply> | undefined; }): Post
  signUp(name: string, password: string): Promise<User>
  login(name: string, password: string): Promise<User>
  logout(): Promise<void>
  promote(ref: OpleRefLike<User>, secret?: string | undefined): Promise<void>
  ban(ref: OpleRefLike<User>, banned?: boolean): Promise<void>
}

interface Signals {
  test(handler: (ref: OpleRef<Post>) => boolean | void): OpleListener
  test(target: Post, handler: () => boolean | void): OpleListener
}

declare const console: any

const backend = defineBackend<Collections, Functions, Signals>({
  onError: console.error,
  protocol: OpleProtocol.ws,
  url: "ws://localhost:3000/@ople-dev",
})

export default backend

const { functions, signals } = backend

export const loadPosts = functions.loadPosts
export const loadReplies = functions.loadReplies
export const publish = makeCreator(functions.publish, "text")
export const reply = makeCreator(functions.reply, "text,post,parent")
export const signUp = functions.signUp
export const login = functions.login
export const logout = functions.logout
export const promote = functions.promote
export const ban = functions.ban

export const test = signals.test

export interface User {
  name: string
  password: string
  banned?: boolean
  admin?: boolean
}

export interface Post {
  text: string
  author: OpleRef<User>
}

export interface Reply {
  text: string
  author: OpleRef<User>
  parent?: OpleRef<Reply>
  post: OpleRef<Post>
}