/**
 * DO NOT EDIT THIS DIRECTLY!
 * Generated by @ople/codegen
 */
import { User } from "@ople/backend"

declare module "@ople/backend" {
  export interface Signals {
    test(ref: OpleRef<Post>): void
  }
  export interface User {
    name: string
    password: string
    banned?: boolean
    admin?: boolean
  }
  export interface OpleDocuments {
    users: User
    posts: Post
    replies: Reply
  }
  export interface OpleCollections {
    users: any
    posts: any
    replies: any
  }
  export interface CallerMeta {
    admin?: boolean
  }
}

export { User }

export interface Post {
  text: string
  author: OpleRef<User>
}

export interface Reply {
  text: string
  author: OpleRef<User>
  parent?: OpleRef<Reply>
  post: OpleRef<Post>
}